### ISSUE TITLE
Configuration warning

### ISSUE THREAD

**Issue by s4nt14go** [DianaIonita/serverless-api-gateway-throttling#13]
Hello Dianalonita! Thanks for your plugin, it's very helpful!

When I deploy I get this warning:
```
Serverless: Configuration warning:
Serverless:   at 'functions.create.events[0].http': unrecognized property 'throttling'
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```
I'm using:
```
Framework Core: 2.9.0
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.3.0
```

Also I found that the line `throttling:` must be the next line following `method: x` to work

Thanks

**Comment by DianaIonita** [comment]
Hi @s4nt14go,

Thanks for raising the issue.
If you use the latest version of the serverless framework, [2.16.0](https://github.com/serverless/serverless/releases/tag/v2.16.0) and the latest version of this plugin, [1.1.0](https://github.com/DianaIonita/serverless-api-gateway-throttling/releases/tag/1.1.0), do you still see validation errors?

**Comment by s4nt14go** [comment]
Hey @DianaIonita,

Updating to serverless@2.16.0 fixed both issues!

Many thanks for your help!
