### ISSUE TITLE
Error: error is thrown if stack doesn't exist

### ISSUE THREAD

**Issue by alligator2005** [DianaIonita/serverless-api-gateway-throttling#28]
Trying to deploy application with `serverless-api-gateway-throttling` plugin when there is no already existing stack.
Unfortunately plugin fails trying to get **Stacks[0]** value of undefined

Exact place where the code fails
<img width="904" alt="image" src="https://user-images.githubusercontent.com/47612379/182118484-da131ac0-868b-4b30-ae7e-512373ecc9d8.png">

**Comment by DianaIonita** [comment]
Thanks @alligator2005,
You can find this fix in the latest release: https://github.com/DianaIonita/serverless-api-gateway-throttling/releases/tag/2.0.2
