### ISSUE TITLE
Throttling on a service level is not working

### ISSUE THREAD

**Issue by patrickwerz** [DianaIonita/serverless-api-gateway-throttling#4]
Hi Diana, 
thanks for this plugin. I just deployed my sls project. Unfortunatelly, the throttling on the function level hasn't changed. It is still "Inheriting from stage".
Do you have any idea what the reason could be? I configured my service sls file as you did in the readme.

Thanks again,
Patrick

**Comment by DianaIonita** [comment]
Hi @patrickwerz,

Would you mind sharing the Serverless Framework version you're using and the `serverless.yml` configuration please?

**Comment by patrickwerz** [comment]
> Hi @patrickwerz,
> 
> Would you mind sharing the Serverless Framework version you're using and the `serverless.yml` configuration please?

Can I send you the file non-publicly?

**Comment by patrickwerz** [comment]
Hi Diana,
Can I send you the file non-publicly?
Best regards,
Patrick

Am Fr., 20. März 2020 um 20:11 Uhr schrieb Diana Ionita <
notifications@github.com>:

**Comment by patrickwerz** [comment]
Hi Diana, 
I anonymized the sls file. You can see the service level throttling at "provisioningServiceV3" .

Thanks for your help
Patrick
`service: iot-provisioning-service
package:
  exclude:
    - './node_modules/**'
provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  environment:
    stage: ${self:custom.stage}
    aws_region: ${self:provider.region}
  apiKeys:
    - name: xxx-api-key-${self:custom.stage}
      value: ${env:api_key}
  memorySize: 256
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:PutMetricFilter
        - logs:PutRetentionPolicy
      Resource:
        - '*'
custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500
  prune:
    automatic: true
    number: 3
  stage: ${env:stage}
  obj_pre: ${self:service}-${self:custom.stage}
  base_domain_dev: 'iot.dev.xxx.cloud'
  base_domain_stg: 'iot.stg.xxx.cloud'
  base_domain_prd: 'iot.xxx.cloud'
  iot_policy: StandardIoTPolicy_${self:custom.stage}
  iot:
    rules:
      telemetry_v3:
        name: 'iot_data_platform_telemetry_v3_${self:custom.stage}'
  pythonRequirements:
    dockerizePip: false
  telemetry_topic: ${cf:iot-data-platform-${self:custom.stage}.IoTTelemetryBasicIngestionTopicName}
  customDomain:
    domainName: 'cfg.${self:custom.base_domain_${self:custom.stage}}'
    stage: ${self:custom.stage}
    certificateName: '*.${self:custom.base_domain_${self:custom.stage}}'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
  token_validation:
    dev:
      auth_url: 'directory.xxx.xxx.cloud'
      auth_path: '/api/v1/jwt_public_keys.json'
      auth_issuer: 'ZAI'
      auth_audience: 'xxx'
    stg:
      auth_url: 'directory.xxx.xxx.cloud'
      auth_path: '/api/v1/jwt_public_keys.json'
      auth_issuer: 'ZAI'
      auth_audience: 'xxx'
    prd:
      auth_url: 'directory.xxx.xxx'
      auth_path: '/api/v1/jwt_public_keys.json'
      auth_issuer: 'ZAI'
      auth_audience: 'xxx'
  auth_scopes:
      dev:
        configuration:
          v3:
            Fn::Join:
              - '|'
              - - 'xxx.onprem.rw'
        provisioning:
          v3:
            Fn::Join:
              - '|'
              - - 'xxx.onprem.rw'
      stg:
        configuration:
          v3:
            Fn::Join:
              - '|'
              - - 'xxx.onprem.rw'
        provisioning:
          v3:
            Fn::Join:
              - '|'
              - - 'xxx.onprem.rw'
      prd:
        configuration:
          v3:
            Fn::Join:
              - '|'
              - - 'xxx.onprem.rw'
        provisioning:
          v3:
            Fn::Join:
              - '|'
              - - 'xxx.onprem.rw'

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-api-gateway-throttling
functions:
  provisioningService:
    handler: src/api_provisioning/api_provisioning.handler
    environment:
      iot_policy_name: ${self:custom.iot_policy}
      base_path: 'v1'
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:AttachThingPrincipal
          - iot:AddThingToThingGroup
          - iot:AttachPolicy
          - iot:DescribeThingGroup
          - iot:CreatePolicy
          - iot:CreateThing
          - iot:CreateThingGroup
          - iot:RegisterCertificate
        Resource: '*'
      - Effect: 'Allow'
        Action:
          - ssm:GetParameters
        Resource: 'arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/iot/${self:custom.stage}/intermediateCA/*'
    events:
      - http:
          path: v1/provisioning/
          method: post
          private: true

  provisioningServiceV2:
    handler: src/api_provisioning/api_provisioning.handler
    environment:
      iot_policy_name: ${self:custom.iot_policy}
      base_path: 'v2'
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:AttachThingPrincipal
          - iot:AddThingToThingGroup
          - iot:AttachPolicy
          - iot:DescribeThingGroup
          - iot:CreatePolicy
          - iot:CreateThing
          - iot:CreateThingGroup
          - iot:RegisterCertificate
        Resource: '*'
      - Effect: 'Allow'
        Action:
          - ssm:GetParameters
        Resource: 'arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/iot/${self:custom.stage}/intermediateCA/*'
    events:
      - http:
          path: v2/provisioning/
          method: post
          private: true

  provisioningServiceV3:
    handler: src/api_provisioning_v3/api_provisioning.handler
    environment:
      iot_policy_name: ${self:custom.iot_policy}
      base_path: 'v3'
      required_scopes: ${self:custom.auth_scopes.${self:custom.stage}.provisioning.v3}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:AttachThingPrincipal
          - iot:AddThingToThingGroup
          - iot:AttachPolicy
          - iot:DescribeThingGroup
          - iot:CreatePolicy
          - iot:CreateThing
          - iot:CreateThingGroup
          - iot:RegisterCertificate
        Resource: '*'
      - Effect: 'Allow'
        Action:
          - ssm:GetParameters
        Resource: 'arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/iot/${self:custom.stage}/intermediateCA/*'
    events:
      - http:
          path: v3/provisioning/
          method: post
          throttling:
            maxRequestsPerSecond: 5
            maxConcurrentRequests: 5
          authorizer:
            name: auth
            resultTtlInSeconds: 0



  configureService:
    handler: src/api_configuration/api_configuration.handler
    environment:
      telemetry_topic: ${self:custom.telemetry_topic}
      base_path: 'v1'
      minimum_software_version: '1.0.0'
      mqtt_port: 8883
      server_cert_link: 'https://www.amazontrust.com/repository/AmazonRootCA1.pem'
      provisioning_url_dev: 'https://cfg.iot.dev.xxx.cloud'
      provisioning_url_stg: 'https://cfg.iot.stg.xxx.cloud'
      provisioning_url_prd: 'https://cfg.iot.xxx.cloud'
      provisioning_path: 'provisioning'
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:DescribeEndpoint
        Resource: '*'
    events:
      - http:
          path: v1/configuration/{senderId}
          method: get
          private: true

  configureServiceV2:
    handler: src/api_configuration/api_configuration.handler
    environment:
      telemetry_topic: ${self:custom.telemetry_topic}
      base_path: 'v2'
      minimum_software_version: '1.0.0'
      mqtt_port: 8883
      server_cert_link: 'https://www.amazontrust.com/repository/AmazonRootCA1.pem'
      provisioning_url_dev: 'https://cfg.iot.dev.xxx.cloud'
      provisioning_url_stg: 'https://cfg.iot.stg.xxx.cloud'
      provisioning_url_prd: 'https://cfg.iot.xxx.cloud'
      provisioning_path: 'provisioning'
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:DescribeEndpoint
        Resource: '*'
    events:
      - http:
          path: v2/configuration/
          method: get
          private: true

  configureServiceV3:
    handler: src/api_configuration_v3/api_configuration.handler
    environment:
      telemetry_topic: '$aws/rules/${self:custom.iot.rules.telemetry_v3.name}'
      base_path: 'v3'
      minimum_software_version: '1.0.0'
      mqtt_port: 8883
      server_cert_link: 'https://www.amazontrust.com/repository/AmazonRootCA1.pem'
      provisioning_url_dev: 'https://cfg.iot.dev.xxx.cloud'
      provisioning_url_stg: 'https://cfg.iot.stg.xxx.cloud'
      provisioning_url_prd: 'https://cfg.iot.xxx.cloud'
      provisioning_path: 'provisioning'
      required_scopes: ${self:custom.auth_scopes.${self:custom.stage}.configuration.v3}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:DescribeEndpoint
        Resource: '*'
    events:
      - http:
          path: v3/configuration/
          method: get
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  auth:
    handler: src/authorization/auth.handler
    environment:
      AUTH_DOMAIN: ${self:custom.token_validation.${self:custom.stage}.auth_url}
      AUTH_PATH: ${self:custom.token_validation.${self:custom.stage}.auth_path}
      AUTH_ISSUER: ${self:custom.token_validation.${self:custom.stage}.auth_issuer}
      AUTH_AUDIENCE: ${self:custom.token_validation.${self:custom.stage}.auth_audience}
    package:
      exclude:
         - '**'
      include:
         - './src/util/**'
         - './src/common_authorization/**'

  iotResourceManager:
    handler: infrastructure/iot_resources/iot_resources.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - iot:AttachPolicy
          - iot:DescribeThingGroup
          - iot:GetPolicy
          - iot:CreatePolicy
          - iot:CreatePolicyVersion
          - iot:DeletePolicyVersion
          - iot:ListPolicyVersions
          - iot:CreateThingGroup
        Resource: '*'

resources:
  Resources:

    CustomIotResourceInvocation:
      Type: 'Custom::IotResourceManagerInvocation'
      Properties:
        SomeRandomProperty: ${env:random} #https://github.com/serverless/serverless/issues/4483
        ServiceToken:
          Fn::GetAtt: [ IotResourceManagerLambdaFunction, Arn ]

    IoTtoKinesisTopicRule:
      Type: 'AWS::IoT::TopicRule'
      Properties:
        RuleName: ${self:custom.iot.rules.telemetry_v3.name}
        TopicRulePayload:
          Sql: "
            SELECT *,
              topic(2) as clientid,
              topic(1) as orgid,
              topic() as topic,
              principal() as principal,
              '${self:custom.iot.rules.telemetry_v3.name}' as rule
          "
          RuleDisabled: false
          AwsIotSqlVersion: '2016-03-23'
          Actions:
            - Kinesis:
                RoleArn: ${cf:iot-data-platform-${self:custom.stage}.IoTtoKinesisRoleArn}
                StreamName: ${cf:iot-data-platform-${self:custom.stage}.rawEventsStreamName}
                PartitionKey:
                  Fn::Join: ['', ['$', '{principal()}']]`

**Comment by DianaIonita** [comment]
Hi @patrickwerz,

I tried out a configuration like the one you provided and it seems to work. The throttling settings are correct at stage level and the function with custom settings is shown as overriding throttling settings.

I'm using the latest version of the plugin and the latest version of the Serverless framework, is that what you're using as well?
